language:
  - python

cache:
  - pip

python:
  - "3.6"

jobs:
  include:
    - name: Run tests
      services: |
        postgresql
      install: |
        pip install -r requirements.txt
      before_script: |
        psql -c 'create database fantasy_rugby_test;' -U postgres
      script: |
        pytest -v --cov .
      after_success: |
        coveralls

    # - name: Update code on vm instance
    #   before_script: |
    #     echo $pkey > my_key.html
    #     base64 --decode my_key.html > my_key
    #     chmod 400 my_key
    #   # if: branch = develop
    #   # script: |
    #   #   ssh -i my_key -o StrictHostKeyChecking=no arthur@35.225.74.56  \
    #   #   "cd /home/app/fp/ && git pull origin develop && \
    #   #   source /home/app/fl_env/bin/activate && \
    #   #   pip install -r requirements.txt && python3 manage.py db upgrade && \
    #   #   sudo service fp restart && sudo service nginx restart"
