"""empty message

Revision ID: 09b578afd353
Revises: 25c379b63ef6
Create Date: 2020-05-12 16:54:15.320278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09b578afd353'
down_revision = '25c379b63ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_team_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fantasyteam_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('is_sub', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fantasyteam_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('fantasyteam_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasyteam_players',
    sa.Column('fantasyteam_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fantasyteam_id'], ['fantasy_teams.id'], name='fantasyteam_players_fantasyteam_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='fantasyteam_players_player_id_fkey')
    )
    op.drop_table('fantasy_team_players')
    # ### end Alembic commands ###
