"""empty message

Revision ID: 25c379b63ef6
Revises: ba30f56c4130
Create Date: 2020-05-12 01:55:38.958699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25c379b63ef6'
down_revision = 'ba30f56c4130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'articles', ['uuid'])
    op.add_column('fantasy_leagues', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'fantasy_leagues', ['uuid'])
    op.add_column('fantasy_teams', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'fantasy_teams', ['uuid'])
    op.add_column('fantasyleague_teams', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'fantasyleague_teams', ['uuid'])
    op.add_column('fixtures', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'fixtures', ['uuid'])
    op.add_column('gameweeks', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'gameweeks', ['uuid'])
    op.add_column('players', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'players', ['uuid'])
    op.add_column('seasons', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'seasons', ['uuid'])
    op.add_column('teams', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'teams', ['uuid'])
    op.add_column('users', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'uuid')
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'uuid')
    op.drop_constraint(None, 'seasons', type_='unique')
    op.drop_column('seasons', 'uuid')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'uuid')
    op.drop_constraint(None, 'gameweeks', type_='unique')
    op.drop_column('gameweeks', 'uuid')
    op.drop_constraint(None, 'fixtures', type_='unique')
    op.drop_column('fixtures', 'uuid')
    op.drop_constraint(None, 'fantasyleague_teams', type_='unique')
    op.drop_column('fantasyleague_teams', 'uuid')
    op.drop_constraint(None, 'fantasy_teams', type_='unique')
    op.drop_column('fantasy_teams', 'uuid')
    op.drop_constraint(None, 'fantasy_leagues', type_='unique')
    op.drop_column('fantasy_leagues', 'uuid')
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'uuid')
    # ### end Alembic commands ###
