"""empty message

Revision ID: 366d638a8675
Revises: eb6be5255f92
Create Date: 2021-11-24 13:39:36.299655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366d638a8675'
down_revision = 'eb6be5255f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fantasy_team_gameweek', sa.Column('game_week_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_fantasy_team_gameweek', 'game_week_points')
    # ### end Alembic commands ###
