"""empty message

Revision ID: 41018db991a0
Revises: 9f42d6913efe
Create Date: 2020-06-02 13:54:51.104308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41018db991a0'
down_revision = '9f42d6913efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_teams',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('team_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    op.add_column('users', sa.Column(
        'first_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column(
        'gender', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column(
        'last_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('phone_number',
                                     sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column(
        'receive_club_notifications', sa.Boolean(), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(
        length=120), autoincrement=False, nullable=False))
    op.drop_column('users', 'receive_club_notifications')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'first_name')
    op.drop_table('user_teams')
    # ### end Alembic commands ###
