"""empty message

Revision ID: 44893a054e93
Revises: 58854502bdcc
Create Date: 2020-10-19 20:43:01.136022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44893a054e93'
down_revision = '58854502bdcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_team_player_gameweeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('player_gameweek_id', sa.Integer(), nullable=True),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.Column('is_sub', sa.Boolean(), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=True),
    sa.Column('is_vice_captain', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['player_gameweek_id'], ['player_gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('fantasy_team_player_gameweek')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_table('fantasy_team_player_gameweek',
    sa.Column('player_gameweek_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fantasy_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], name='fantasy_team_player_gameweek_fantasy_team_id_fkey'),
    sa.ForeignKeyConstraint(['player_gameweek_id'], ['player_gameweeks.id'], name='fantasy_team_player_gameweek_player_gameweek_id_fkey')
    )
    op.drop_table('fantasy_team_player_gameweeks')
    # ### end Alembic commands ###
