"""empty message

Revision ID: 46202581afb8
Revises: b0f2f4d5ac04
Create Date: 2020-05-21 03:28:47.902038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46202581afb8'
down_revision = 'b0f2f4d5ac04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gameweeks', sa.Column('assists', sa.Integer(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('drop_goals', sa.Integer(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('man_of_the_match', sa.Boolean(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('penalty_kicks', sa.Integer(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('starting_appearance', sa.Boolean(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('sub_appearance', sa.Boolean(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('tries', sa.Integer(), nullable=True))
    op.drop_column('player_gameweeks', 'trys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gameweeks', sa.Column('trys', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player_gameweeks', 'tries')
    op.drop_column('player_gameweeks', 'sub_appearance')
    op.drop_column('player_gameweeks', 'starting_appearance')
    op.drop_column('player_gameweeks', 'penalty_kicks')
    op.drop_column('player_gameweeks', 'man_of_the_match')
    op.drop_column('player_gameweeks', 'drop_goals')
    op.drop_column('player_gameweeks', 'assists')
    # ### end Alembic commands ###
