"""empty message

Revision ID: 4f1be02727b2
Revises: 41018db991a0
Create Date: 2020-07-02 10:44:22.282829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1be02727b2'
down_revision = '41018db991a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('away_team_result', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('home_team_result', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'home_team_result')
    op.drop_column('fixtures', 'away_team_result')
    # ### end Alembic commands ###
