"""empty message

Revision ID: 52e4b7f93aaa
Revises: a51386c724ba
Create Date: 2020-03-21 19:22:54.726810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e4b7f93aaa'
down_revision = 'a51386c724ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('away_team', sa.String(length=180), nullable=True))
    op.add_column('fixtures', sa.Column('home_team', sa.String(length=180), nullable=True))
    op.drop_constraint('fixtures_home_team_id_fkey', 'fixtures', type_='foreignkey')
    op.drop_constraint('fixtures_away_team_id_fkey', 'fixtures', type_='foreignkey')
    op.drop_column('fixtures', 'away_team_id')
    op.drop_column('fixtures', 'home_team_id')
    op.add_column('teams', sa.Column('jersey', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'jersey')
    op.add_column('fixtures', sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fixtures', sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fixtures_away_team_id_fkey', 'fixtures', 'teams', ['away_team_id'], ['id'])
    op.create_foreign_key('fixtures_home_team_id_fkey', 'fixtures', 'teams', ['home_team_id'], ['id'])
    op.drop_column('fixtures', 'home_team')
    op.drop_column('fixtures', 'away_team')
    # ### end Alembic commands ###
