"""empty message

Revision ID: 596de770e40e
Revises: bc473c28a4b8
Create Date: 2020-09-14 19:19:50.217494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596de770e40e'
down_revision = 'bc473c28a4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixtures', 'away_team_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('fixtures', 'home_team_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('player_gameweeks', 'fixture_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_gameweeks', 'fixture_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('fixtures', 'home_team_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('fixtures', 'away_team_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
