"""empty message

Revision ID: 5a2b2b6d50b6
Revises: 596de770e40e
Create Date: 2020-09-15 01:52:04.907551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2b2b6d50b6'
down_revision = '596de770e40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_gameweeks', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_gameweeks', 'fixture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
