"""empty message

Revision ID: 5ad765dba23c
Revises: cfbe60783479
Create Date: 2020-07-27 17:43:01.658790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad765dba23c'
down_revision = 'cfbe60783479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameweeks', sa.Column('is_current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameweeks', 'is_current')
    # ### end Alembic commands ###
