"""empty message

Revision ID: 694099c1d6a1
Revises: fcb51e2264dd
Create Date: 2020-09-14 12:05:08.605362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694099c1d6a1'
down_revision = 'fcb51e2264dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gameweeks', sa.Column(
        'fixture_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'player_gameweeks',
                          'fixtures', ['fixture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_gameweeks', type_='foreignkey')
    op.drop_column('player_gameweeks', 'fixture_id')
    # ### end Alembic commands ###
