"""empty message

Revision ID: 77e4bb2f50dd
Revises: a3ea154fa01a
Create Date: 2021-09-06 23:14:33.669725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e4bb2f50dd'
down_revision = 'a3ea154fa01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fantasy_team_players', sa.Column('player_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_team_players', 'player_order')
    # ### end Alembic commands ###
