"""empty message

Revision ID: 824ba3dd5696
Revises: 44893a054e93
Create Date: 2020-10-20 02:00:34.807965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824ba3dd5696'
down_revision = '44893a054e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fantasy_team_player_gameweeks', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_team_player_gameweeks', 'points')
    # ### end Alembic commands ###
