"""empty message

Revision ID: 884b8ffc5805
Revises: 4f1be02727b2
Create Date: 2020-07-02 17:53:56.644038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884b8ffc5805'
down_revision = '4f1be02727b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image', sa.String(length=180), nullable=True))
    op.add_column('articles', sa.Column('is_highlight', sa.Boolean(), nullable=True))
    op.add_column('seasons', sa.Column('is_current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'is_current')
    op.drop_column('articles', 'is_highlight')
    op.drop_column('articles', 'image')
    # ### end Alembic commands ###
