"""empty message

Revision ID: 8f4a514f86fa
Revises: 09b578afd353
Create Date: 2020-05-14 14:52:10.402609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4a514f86fa'
down_revision = '09b578afd353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fantasy_team_players', sa.Column('is_captain', sa.Boolean(), nullable=True))
    op.add_column('fantasy_team_players', sa.Column('is_vice_captain', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_team_players', 'is_vice_captain')
    op.drop_column('fantasy_team_players', 'is_captain')
    # ### end Alembic commands ###
