"""empty message

Revision ID: 94cf0128a446
Revises: 366d638a8675
Create Date: 2022-02-03 23:14:37.688117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cf0128a446'
down_revision = '366d638a8675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fantasy_leagues', sa.Column('code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_leagues', 'code')
    # ### end Alembic commands ###
