"""empty message

Revision ID: 96b6cfbbce58
Revises: d2003163ccff
Create Date: 2019-12-08 16:18:23.297982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b6cfbbce58'
down_revision = 'd2003163ccff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fantasy_teams', sa.Column('captain', sa.Integer(), nullable=True))
    op.add_column('fantasy_teams', sa.Column('vice_captain', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('game_week_id', sa.Integer(), nullable=False))
    op.drop_constraint('fixtures_season_id_fkey', 'fixtures', type_='foreignkey')
    op.create_foreign_key(None, 'fixtures', 'gameweeks', ['game_week_id'], ['id'])
    op.drop_column('fixtures', 'season_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.create_foreign_key('fixtures_season_id_fkey', 'fixtures', 'seasons', ['season_id'], ['id'])
    op.drop_column('fixtures', 'game_week_id')
    op.drop_column('fantasy_teams', 'vice_captain')
    op.drop_column('fantasy_teams', 'captain')
    op.drop_table('gameweeks')
    # ### end Alembic commands ###
