"""empty message

Revision ID: 9f42d6913efe
Revises: 46202581afb8
Create Date: 2020-05-27 23:37:13.637187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f42d6913efe'
down_revision = '46202581afb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gameweeks', sa.Column('gameweek_points', sa.Integer(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('red_card', sa.Boolean(), nullable=True))
    op.add_column('player_gameweeks', sa.Column('yellow_card', sa.Boolean(), nullable=True))
    op.drop_column('player_gameweeks', 'yellow_cards')
    op.drop_column('player_gameweeks', 'red_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_gameweeks', sa.Column('red_cards', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('player_gameweeks', sa.Column('yellow_cards', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('player_gameweeks', 'yellow_card')
    op.drop_column('player_gameweeks', 'red_card')
    op.drop_column('player_gameweeks', 'gameweek_points')
    # ### end Alembic commands ###
