"""empty message

Revision ID: 9fdc66f0ed83
Revises: 5ad765dba23c
Create Date: 2020-09-01 23:47:29.559721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdc66f0ed83'
down_revision = '5ad765dba23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatasy_team_player_gameweek',
    sa.Column('player_gameweek_id', sa.Integer(), nullable=True),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['player_gameweek_id'], ['player_gameweeks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fatasy_team_player_gameweek')
    # ### end Alembic commands ###
