"""empty message

Revision ID: a3ea154fa01a
Revises: ed7ba8a321c3
Create Date: 2021-06-30 16:20:20.966091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ea154fa01a'
down_revision = 'ed7ba8a321c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    # ### end Alembic commands ###
