"""empty message

Revision ID: a4c67c1befbb
Revises: 9fdc66f0ed83
Create Date: 2020-09-02 00:47:17.263945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c67c1befbb'
down_revision = '9fdc66f0ed83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_team_player_gameweek',
    sa.Column('player_gameweek_id', sa.Integer(), nullable=True),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['player_gameweek_id'], ['player_gameweeks.id'], )
    )
    op.drop_table('fatasy_team_player_gameweek')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatasy_team_player_gameweek',
    sa.Column('player_gameweek_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fantasy_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], name='fatasy_team_player_gameweek_fantasy_team_id_fkey'),
    sa.ForeignKeyConstraint(['player_gameweek_id'], ['player_gameweeks.id'], name='fatasy_team_player_gameweek_player_gameweek_id_fkey')
    )
    op.drop_table('fantasy_team_player_gameweek')
    # ### end Alembic commands ###
