"""empty message

Revision ID: a51386c724ba
Revises: 96b6cfbbce58
Create Date: 2020-03-12 20:14:00.716176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51386c724ba'
down_revision = '96b6cfbbce58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('away_team_id', sa.Integer(), nullable=False))
    op.add_column('fixtures', sa.Column('home_team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fixtures', 'teams', ['away_team_id'], ['id'])
    op.create_foreign_key(None, 'fixtures', 'teams', ['home_team_id'], ['id'])
    op.drop_column('fixtures', 'home_team')
    op.drop_column('fixtures', 'away_team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('away_team', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    op.add_column('fixtures', sa.Column('home_team', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.drop_column('fixtures', 'home_team_id')
    op.drop_column('fixtures', 'away_team_id')
    # ### end Alembic commands ###
