"""empty message

Revision ID: ba30f56c4130
Revises: de68fdcf4186
Create Date: 2020-03-27 18:06:12.141918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba30f56c4130'
down_revision = 'de68fdcf4186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('jersey', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'jersey')
    # ### end Alembic commands ###
