"""empty message

Revision ID: bc473c28a4b8
Revises: 694099c1d6a1
Create Date: 2020-09-14 18:36:32.149744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc473c28a4b8'
down_revision = '694099c1d6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column(
        'away_team_id', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column(
        'home_team_id', sa.Integer(), nullable=True))
    op.drop_column('fixtures', 'away_team')
    op.drop_column('fixtures', 'home_team')
    op.alter_column('player_gameweeks', 'fixture_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_gameweeks', 'fixture_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.add_column('fixtures', sa.Column('home_team', sa.VARCHAR(
        length=180), autoincrement=False, nullable=False))
    op.add_column('fixtures', sa.Column('away_team', sa.VARCHAR(
        length=180), autoincrement=False, nullable=False))
    op.drop_column('fixtures', 'home_team_id')
    op.drop_column('fixtures', 'away_team_id')
    # ### end Alembic commands ###
