"""empty message

Revision ID: c02773a9b567
Revises: 824ba3dd5696
Create Date: 2020-11-09 17:04:50.685275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02773a9b567'
down_revision = '824ba3dd5696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('gameweeks', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameweeks', 'name')
    op.drop_column('fixtures', 'name')
    # ### end Alembic commands ###
