"""empty message

Revision ID: cfbe60783479
Revises: 884b8ffc5805
Create Date: 2020-07-02 18:36:07.242795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbe60783479'
down_revision = '884b8ffc5805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'points')
    # ### end Alembic commands ###
