"""empty message

Revision ID: de68fdcf4186
Revises: 52e4b7f93aaa
Create Date: 2020-03-25 00:56:47.417643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de68fdcf4186'
down_revision = '52e4b7f93aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'jersey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('jersey', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
