"""empty message

Revision ID: eb6be5255f92
Revises: 77e4bb2f50dd
Create Date: 2021-11-16 15:04:07.086682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb6be5255f92'
down_revision = '77e4bb2f50dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fantasy_team_gameweek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('transfers', sa.Integer(), nullable=True),
    sa.Column('points_deductible', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.Column('game_week_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['game_week_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_fantasy_team_gameweek')
    # ### end Alembic commands ###
