"""empty message

Revision ID: ed7ba8a321c3
Revises: c02773a9b567
Create Date: 2020-11-18 17:37:16.763498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7ba8a321c3'
down_revision = 'c02773a9b567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'fixtures', 'teams', ['home_team_id'], ['id'])
    op.create_foreign_key(None, 'fixtures', 'teams', ['away_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    # ### end Alembic commands ###
