"""empty message

Revision ID: fcb51e2264dd
Revises: a4c67c1befbb
Create Date: 2020-09-11 01:32:23.822292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb51e2264dd'
down_revision = 'a4c67c1befbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points_deductible', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('transfers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transfers')
    op.drop_column('users', 'points_deductible')
    # ### end Alembic commands ###
